camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest # the URL pointing to the Camunda Platform Runtime REST API
  lock-duration: 120000 # defines how many milliseconds the External Tasks are locked until they can be fetched again
  subscriptions:
    load:
      variable-names: []
      process-definition-key: myloadtestprocess